//go:build ppc64le

package matchlen

// bulkMatch compares a and b in 16-byte VSX blocks up to limit, returning the
// match length. Generated by go-asmgen (bulkmatch_ppc64le_gen.go), in
// bulkmatch_ppc64le.s.
func bulkMatch(a, b []byte, limit int) int
